#Auto-generated by the projectmake utility
BUILD_DIR = .build

.PHONY: all ship purge clean

# 1. The default target: ensures .build exists, runs cmake, then builds
all:
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=OFF
	@cmake --build $(BUILD_DIR) --target lsj -- --no-print-directory

ship:
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR) -DFORCE_JSL_CLONE=ON
	@cmake --build $(BUILD_DIR) --target lsj -- --no-print-directory

# 3. Clean up only the build artifacts
purge:
	@echo "Removing all build files"
	@rm -rf $(BUILD_DIR)
	@rm -f lsj

clean:
	@echo "Rebuilding from scratch"
	@make purge
	@make all --no-print-directory
