#Auto-generated by the projectmake utility
BUILD_DIR = .build

.PHONY: all test clean

# 1. The default target: ensures .build exists, runs cmake, then builds
all:
	@mkdir -p $(BUILD_DIR)
	@cmake -S . -B $(BUILD_DIR)
	@cmake --build $(BUILD_DIR) --target ssb_run -- --no-print-directory


# 3. Clean up only the build artifacts
purge:
	@echo "Removing all build files"
	@rm -rf $(BUILD_DIR)
	@rm -f unit ssb_run

clean:
	@echo "Rebuilding from scratch"
	@make purge
	@make all --no-print-directory
