#include <JSL.h>
#include <JSL/Interface/Aggregator.h>

using namespace JSL::Interface;

class ModesObj : public Aggregator<ModesObj>
{
  public:
	//! @brief If true, enables source code alteration to fix CRTP errors
	//! @alias fix, f
	bool ActiveFix = false;

#include "Settings.ModesObj.autogen"
};

// @name Inbuilt Strings
class StringsObj : public Aggregator<StringsObj>
{
  public:
	// @brief The extension given to all autogenerated files to indicate that they were generated with this tool
	// @alias ext extension
	std::string FileExtension = ".autogen";

	std::string TemplateName = "Wrapper";
	std::string ObjectName = "W";

#include "Settings.StringsObj.autogen"
};

//! @command [filename] A file to be acted upon
class SettingsObj : public JSL::Interface::Aggregator<SettingsObj>
{
  public:
	//! @brief Verbose mode; prints diagnostic information
	//! @alias v, verbose
	bool Verbose = false;

	//! @brief Quiet mode
	//! @alias q
	bool Quiet = false;

	//! @name Header Extensions
	//! @brief File extensions which are used as signfiers of header files during validation checks
	//! @alias header
	std::vector<std::string> extensions = {".h", ".hpp"};

	ModesObj Modes;
	StringsObj Strings;
#include "Settings.SettingsObj.autogen"
};
extern SettingsObj Settings;
