#include <JSL.h>
#include <JSL/Interface/Aggregator.h>

using namespace JSL::Interface;

class ModesObj : public Aggregator<ModesObj>
{
  public:
	//! @brief If true, enables source code alteration to fix CRTP errors
	//! @alias fix, f
	bool ActiveFix = false;

#include "Settings.ModesObj.autogen"
};

// @name Inbuilt Strings
class StringsObj : public Aggregator<StringsObj>
{
  public:
	// @brief The name given to all autogenerated files to indicate that they were generated with this tool
	// @alias suffix
	std::string Suffix = ".autogen";
	std::string TemplateName = "Wrapper";
	std::string ObjectName = "W";

#include "Settings.StringsObj.autogen"
};

class SettingsObj : public JSL::Interface::Aggregator<SettingsObj>
{
  public:
	//! @brief Verbose
	//! @alias v, verbose
	bool Verbose = false;
	//! @brief Quiet mode
	//! @alias q
	bool Quiet = false;
	std::vector<std::string> extensions = {".h", ".hpp"};

	ModesObj Modes;
	StringsObj Strings;
#include "Settings.SettingsObj.autogen"
};
extern SettingsObj Settings;
